// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcyaZ_C9NFSxDjKtsFNGIBYpQzNir4s9E',
    appId: '1:630312517221:web:59dc96e1877f906596508c',
    messagingSenderId: '630312517221',
    projectId: 'singlemart-ags',
    authDomain: 'singlemart-ags.firebaseapp.com',
    storageBucket: 'singlemart-ags.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1YaTFNRmmf6KqSea0SoLWOQ5Vi7vrG-A',
    appId: '1:630312517221:android:655c3999f237e14d96508c',
    messagingSenderId: '630312517221',
    projectId: 'singlemart-ags',
    storageBucket: 'singlemart-ags.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcGU1-zFBIZ8-GHX6Cm4tYpb7EFrxHZsM',
    appId: '1:630312517221:ios:7780ba15ffd6ccf396508c',
    messagingSenderId: '630312517221',
    projectId: 'singlemart-ags',
    storageBucket: 'singlemart-ags.firebasestorage.app',
    iosBundleId: 'com.example.singlemart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcGU1-zFBIZ8-GHX6Cm4tYpb7EFrxHZsM',
    appId: '1:630312517221:ios:7780ba15ffd6ccf396508c',
    messagingSenderId: '630312517221',
    projectId: 'singlemart-ags',
    storageBucket: 'singlemart-ags.firebasestorage.app',
    iosBundleId: 'com.example.singlemart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcyaZ_C9NFSxDjKtsFNGIBYpQzNir4s9E',
    appId: '1:630312517221:web:0f95a1d5810cf74b96508c',
    messagingSenderId: '630312517221',
    projectId: 'singlemart-ags',
    authDomain: 'singlemart-ags.firebaseapp.com',
    storageBucket: 'singlemart-ags.firebasestorage.app',
  );
}
